### ISSUE TITLE
How long is the training time

### ISSUE THREAD

**Issue by Ayanami2019** [lijx10/DeepI2P#1]
Hello, thanks for sharing your code. I want to follow up your work but may not have enough equipment. What is the GPU you are using, and how long is the training time on the two data sets?

**Comment by lijx10** [comment]
Hi, it takes around 2 days to train on the OxfordRobot car dataset with a sinlge 1080ti.

**Comment by chenpengxin** [comment]
A readme.md would be much appreciated.

**Comment by lijx10** [comment]
Readme was online yesterday! I will try to improve the repo in the future. Thanks!
